// <auto-generated />
namespace BHao.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Aukcija_add_Provizija_Datum_Placanja : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aukcija_add_Provizija_Datum_Placanja));
        
        string IMigrationMetadata.Id
        {
            get { return "201505210554322_Aukcija_add_Provizija_Datum_Placanja"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
