// <auto-generated />
namespace BHao.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Grad_promjena_Ime_u_Naziv : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Grad_promjena_Ime_u_Naziv));
        
        string IMigrationMetadata.Id
        {
            get { return "201505120919028_Grad_promjena_Ime_u_Naziv"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
