// <auto-generated />
namespace BHao.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Poruka_add_Obrisana_za_primalac_i_posiljalac : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Poruka_add_Obrisana_za_primalac_i_posiljalac));
        
        string IMigrationMetadata.Id
        {
            get { return "201505080730477_Poruka_add_Obrisana_za_primalac_i_posiljalac"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
